nb_principal_homepage:
    path:     /
    defaults: { _controller: NBPrincipalBundle:Default:index }

nb_principale_cv:
    path: /cv
    defaults: { _controller: NBPrincipalBundle:Default:cv }
    
nb_admin:
    path: /admin
    defaults: { _controller: NBPrincipalBundle:Default:admin }