# src/NB/SecurityBundle/Resources/config/security_factories.yml
services:
    security.authentication.factory.wsse:
        class:  NB\SecurityBundle\DependencyInjection\Security\Factory\WsseFactory
        tags:
            - { name: security.listener.factory }